apiVersion: v1
kind: Service
metadata:
  name: project-app-svc
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/health"
    prometheus.io/port: "5000"
spec:
  type: NodePort
  selector:
    app: project-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
